default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: pmi_parser_development


test:
  <<: *default
  database: pmi_parser_test
